PROGRAM Task1(INPUT, OUTPUT);
USES
  DOS;
BEGIN
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN(GETENV('REQUEST_METHOD'));
  WRITELN(GETENV('QUERY_STRING'));
  WRITELN(GETENV('CONTENT_LENGHT'));
  WRITELN(GETENV('HTTP_USER_AGENT'));
  WRITELN(GETENV('HTTP_HOST'))
END.

